config:
  target: 'http://localhost:3000'
  phases:
    - duration: 60
      arrivalRate: 100
  payload:
    path: 'users.csv'
    fields:
      - 'username'
      - 'password'
      - 'balance'

scenarios:
  - flow:
      - post:
          url: '/api/signup'
          json:
            username: '{{ username }}'
            password: '{{ password }}'
            balance: '{{ balance }}'
